version: "3.3"  #首先是版本号，别乱写，这个是和Docker版本有对应的
services:   #services里面就是我们所有需要进行编排的服务了
  spring:   #服务名称，随便起
    container_name: app_spring  #一会要创建的容器名称
    build:
      context: ./spring-data
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: app_mysql
    build:
      context: ./mysql-data
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
  redis:
    container_name: app_redis
    image: redis:latest
    ports:
      - "6379:6379"
