spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PBL2
    username: root
    password: liuhang12
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    sava: "/Users/liuhang/Desktop/文件测试"
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    user:
      name: 'admin'
      password: '123456'
      roles:
        - admin
        - use
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'


#logging:
#  level:
#    org.springframework.amqp: DEBUG
#    org.springframework.security: DEBUG


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080